services:
  - type: web
    name: trust-bank
    plan: free
    env: static
    staticPublishPath: .
    buildCommand: ""
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
